AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/electionbuddy-ruby.rb'

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Layout/LineLength:
  Max: 150